name: DuyOla-RDP

on: workflow_dispatch

jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
    - name: Tải xuống Ngrok.
      run: |
        Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
        Invoke-WebRequest https://raw.githubusercontent.com/tuanmuda2019/TuanwaraRDP/main/start.bat -OutFile start.bat
        Invoke-WebRequest https://raw.githubusercontent.com/VuDuyOla/VPS-RDP/main/wallpaper.png -OutFile wallpaper.png
        Invoke-WebRequest https://raw.githubusercontent.com/tuanmuda2019/TuanwaraRDP/main/wallpaper.bat -OutFile wallpaper.bat
        Invoke-WebRequest https://raw.githubusercontent.com/tuanmuda2019/TuanwaraRDP/main/loop.ps1 -OutFile loop.ps1
    - name: Tải xuống Trình khởi chạy.
      run: |
        Invoke-WebRequest https://growtopiagame.com/Growtopia-Installer.exe -OutFile "Growtopia-Installer.exe"
        Invoke-WebRequest https://github.com/tuanmuda2019/TuanwaraRDP/raw/main/keluar%20masuk.exe -OutFile "keluar%20masuk.exe"
      
    - name: Giải nén tệp Ngrok.
      run: Expand-Archive ngrok.zip
    - name: Connecting to your Ngrok account.
      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Kích hoạt quyền truy cập RDP.
      run: | 
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
        Set-WinUserLanguageList -LanguageList tr, en-US -Force
        copy wallpaper.png D:\a\wallpaper.png
        copy wallpaper.bat D:\a\wallpaper.bat
        copy "Growtopia-Installer.exe" "C:\Users\Public\Desktop\Growtopia-Installer.exe"
        copy "keluar%20masuk.exe" "C:\Users\Public\Desktop\keluar%20masuk.exe"
    - name: Tạo đường hầm.
      run: Start-Process Powershell -ArgumentList '-Noexit -Command ".\ngrok\ngrok.exe tcp 3389"'
    - name: Kết nối với RDP của bạn
      run: cmd /c start.bat
    - name: RDP đã sẵn sàng!
      run: | 
       Invoke-WebRequest https://raw.githubusercontent.com/tuanmuda2019/TuanwaraRDP/main/loop.ps1 -OutFile loop.ps1
       ./loop.ps1
